### ISSUE TITLE
3 tests fail

### ISSUE THREAD

**Issue by yurivict** [Martchus/qtutilities#10]
```
    Start 1: qtutilities_run_buttonoverlay_tests
1/3 Test #1: qtutilities_run_buttonoverlay_tests ......Subprocess aborted***Exception:   0.02 sec
    Start 2: qtutilities_run_dialogs_tests
2/3 Test #2: qtutilities_run_dialogs_tests ............Subprocess aborted***Exception:   0.02 sec
    Start 3: qtutilities_run_dbusnotification_tests
3/3 Test #3: qtutilities_run_dbusnotification_tests ...Subprocess aborted***Exception:   0.02 sec

0% tests passed, 3 tests failed out of 3

Total Test time (real) =   0.06 sec

The following tests FAILED:
          1 - qtutilities_run_buttonoverlay_tests (Subprocess aborted)
          2 - qtutilities_run_dialogs_tests (Subprocess aborted)
          3 - qtutilities_run_dbusnotification_tests (Subprocess aborted)
Errors while running CTest
Output from these tests are in: /usr/ports/devel/qtutilities/work/.build/Testing/Temporary/LastTest.log
Use "--rerun-failed --output-on-failure" to re-run the failed cases verbosely.
FAILED: CMakeFiles/test.util 
cd /usr/ports/devel/qtutilities/work/.build && /usr/local/bin/ctest --force-new-ctest-process
ninja: build stopped: subcommand failed.
*** Error code 1
```

Version: 6.13.5
clang-16
FreeBSD 14.0

**Comment by Martchus** [comment]
How would I be able to help you with that? I have no idea how you invoked the build, what the output of the CMake configuration looked like, what versions of certain dependencies you're using, what the general environment you run tests in is and so on.

Maybe you need `export QT_QPA_PLATFORM=offscreen`? Maybe it helps to follow the documentation about invoking the build more closely (the README of c++utilities) or have a look at how I package it for Arch Linux (https://github.com/Martchus/PKGBUILDs/blob/master/qtutilities/qt6/PKGBUILD), e.g. the use of the `check` target could be important.

Otherwise, I suggest to have a look at the configuration output and test logs and see what went actually wrong.

**Comment by yurivict** [comment]
Adding ```QT_QPA_PLATFORM=offscreen``` helped.

Thank you for your help!

**Comment by Martchus** [comment]
Nice, I that was a lucky guess then.
